/**
 * Unit tests for the single-file mirror drift guard in
 * `cli/src/lib/mirror-runner.ts`.
 *
 * Covers the user-facing behaviors for `augx link --mirror` on the
 * single-file adapters (`cursor`, `windsurf`, `copilot`):
 *   1. Unchanged reruns are byte-identical and do not rewrite the target.
 *   2. Managed drift is refused unless `--force` is explicit.
 *   3. Unmarked user content is refused.
 *   4. Forced overwrites preserve a backup under `.augment/mirror-backups/`.
 *   5. A failed forced overwrite restores the original content.
 */

import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import type { ResolvedModule } from '@cli/adapters/types';
import { mirrorModule } from '@cli/lib/mirror-runner';

vi.mock('fs', async () => {
  const actual = await vi.importActual<typeof import('fs')>('fs');
  return {
    ...actual,
    default: actual,
    writeFileSync: vi.fn(actual.writeFileSync),
  };
});

const MODULE_ID = 'coding-standards/single-file-guard';
const MODULE_VERSION = '1.0.0';
const NOW = () => '2026-05-25T12:00:00Z';

function moduleSegment(moduleId: string): string {
  return moduleId.replace(/\//g, '-');
}

function writeRule(root: string, rel: string, body: string): string {
  const abs = path.join(root, rel);
  fs.mkdirSync(path.dirname(abs), { recursive: true });
  fs.writeFileSync(abs, body, 'utf-8');
  return abs;
}

function readModuleFromDisk(moduleRoot: string): ResolvedModule {
  const rulesRoot = path.join(moduleRoot, 'rules');
  const rels = fs.existsSync(rulesRoot) ? fs.readdirSync(rulesRoot).sort() : [];
  return {
    id: MODULE_ID,
    version: MODULE_VERSION,
    rootPath: moduleRoot,
    rulesFiles: rels.map((rel) => ({
      relativePath: `rules/${rel}`,
      content: fs.readFileSync(path.join(rulesRoot, rel), 'utf-8').replace(/\r\n?/g, '\n'),
    })),
    examplesFiles: [],
  };
}

function targetPath(projectRoot: string): string {
  return path.join(
    projectRoot,
    '.windsurf',
    'rules',
    `augx-${moduleSegment(MODULE_ID)}.md`
  );
}

function backupPath(projectRoot: string): string {
  return path.join(
    projectRoot,
    '.augment',
    'mirror-backups',
    '.windsurf',
    'rules',
    `augx-${moduleSegment(MODULE_ID)}.md`
  );
}

function makeTempRoot(): string {
  return fs.mkdtempSync(path.join(os.tmpdir(), 'augx-single-guard-'));
}

describe('mirrorModule: single-file drift guard', () => {
  let tmp: string;
  let moduleRoot: string;

  beforeEach(() => {
    tmp = makeTempRoot();
    moduleRoot = path.join(tmp, 'augment-extensions', 'coding-standards', 'single-file-guard');
    fs.mkdirSync(path.join(moduleRoot, 'rules'), { recursive: true });
    fs.writeFileSync(path.join(moduleRoot, 'rules', 'main.md'), '# guard rule\n', 'utf-8');
  });

  afterEach(() => {
    vi.restoreAllMocks();
    fs.rmSync(tmp, { recursive: true, force: true });
  });

  it('keeps an unchanged windsurf mirror byte-identical on rerun', () => {
    const first = mirrorModule(readModuleFromDisk(moduleRoot), ['windsurf'], {
      projectRoot: tmp,
      augxVersion: '0.0.0-test',
      ignorePatterns: [],
      now: NOW,
      recordedByTarget: new Map(),
    });

    const dest = targetPath(tmp);
    const firstContent = fs.readFileSync(dest, 'utf-8');
    expect(first.entries).toHaveLength(1);
    expect(first.entries[0].mode).toBe('copy');
    expect(firstContent).toContain('<!-- GENERATED BY augx export - DO NOT EDIT -->');
    expect(firstContent).toContain('<!-- source-hash: ');

    const second = mirrorModule(readModuleFromDisk(moduleRoot), ['windsurf'], {
      projectRoot: tmp,
      augxVersion: '0.0.0-test',
      ignorePatterns: [],
      now: NOW,
      recordedByTarget: new Map(first.entries.map((entry) => [entry.targetPath, entry])),
    });

    expect(second.entries).toHaveLength(1);
    expect(fs.readFileSync(dest, 'utf-8')).toBe(firstContent);
    expect(fs.existsSync(backupPath(tmp))).toBe(false);
  });

  it('refuses managed drift without force', () => {
    const first = mirrorModule(readModuleFromDisk(moduleRoot), ['windsurf'], {
      projectRoot: tmp,
      augxVersion: '0.0.0-test',
      ignorePatterns: [],
      now: NOW,
      recordedByTarget: new Map(),
    });

    const dest = targetPath(tmp);
    const tampered = fs.readFileSync(dest, 'utf-8') + '\n<!-- local edit -->\n';
    fs.writeFileSync(dest, tampered, 'utf-8');

    expect(() =>
      mirrorModule(readModuleFromDisk(moduleRoot), ['windsurf'], {
        projectRoot: tmp,
        augxVersion: '0.0.0-test',
        ignorePatterns: [],
        now: NOW,
        recordedByTarget: new Map(first.entries.map((entry) => [entry.targetPath, entry])),
      })
    ).toThrow(/drift|--force/i);

    expect(fs.readFileSync(dest, 'utf-8')).toBe(tampered);
    expect(fs.existsSync(backupPath(tmp))).toBe(false);
  });

  it('refuses unmarked user content without force', () => {
    const dest = targetPath(tmp);
    fs.mkdirSync(path.dirname(dest), { recursive: true });
    fs.writeFileSync(dest, '# handwritten notes\n', 'utf-8');

    expect(() =>
      mirrorModule(readModuleFromDisk(moduleRoot), ['windsurf'], {
        projectRoot: tmp,
        augxVersion: '0.0.0-test',
        ignorePatterns: [],
        now: NOW,
        recordedByTarget: new Map(),
      })
    ).toThrow(/no augx source-hash banner|--force/i);

    expect(fs.readFileSync(dest, 'utf-8')).toBe('# handwritten notes\n');
    expect(fs.existsSync(backupPath(tmp))).toBe(false);
  });

  it('backs up and overwrites a drifted mirror when force is enabled', () => {
    const first = mirrorModule(readModuleFromDisk(moduleRoot), ['windsurf'], {
      projectRoot: tmp,
      augxVersion: '0.0.0-test',
      ignorePatterns: [],
      now: NOW,
      recordedByTarget: new Map(),
    });

    const dest = targetPath(tmp);
    const initial = fs.readFileSync(dest, 'utf-8');
    const tampered = initial + '\n<!-- local edit -->\n';
    fs.writeFileSync(dest, tampered, 'utf-8');

    const second = mirrorModule(readModuleFromDisk(moduleRoot), ['windsurf'], {
      projectRoot: tmp,
      augxVersion: '0.0.0-test',
      ignorePatterns: [],
      now: NOW,
      force: true,
      recordedByTarget: new Map(first.entries.map((entry) => [entry.targetPath, entry])),
    });

    expect(second.entries).toHaveLength(1);
    expect(fs.readFileSync(dest, 'utf-8')).toBe(initial);
    expect(fs.readFileSync(backupPath(tmp), 'utf-8')).toBe(tampered);
  });

  it('restores the original content if a forced overwrite write fails', () => {
    const first = mirrorModule(readModuleFromDisk(moduleRoot), ['windsurf'], {
      projectRoot: tmp,
      augxVersion: '0.0.0-test',
      ignorePatterns: [],
      now: NOW,
      recordedByTarget: new Map(),
    });

    const dest = targetPath(tmp);
    const initial = fs.readFileSync(dest, 'utf-8');
    const tampered = initial + '\n<!-- local edit -->\n';
    fs.writeFileSync(dest, tampered, 'utf-8');

    vi.mocked(fs.writeFileSync).mockImplementationOnce(() => {
      const err = new Error('disk full') as NodeJS.ErrnoException;
      err.code = 'ENOSPC';
      throw err;
    });

    expect(() =>
      mirrorModule(readModuleFromDisk(moduleRoot), ['windsurf'], {
        projectRoot: tmp,
        augxVersion: '0.0.0-test',
        ignorePatterns: [],
        now: NOW,
        force: true,
        recordedByTarget: new Map(first.entries.map((entry) => [entry.targetPath, entry])),
      })
    ).toThrow(/ENOSPC|disk full/);

    expect(fs.readFileSync(dest, 'utf-8')).toBe(tampered);
    expect(fs.readFileSync(backupPath(tmp), 'utf-8')).toBe(tampered);
  });
});
