import chalk from 'chalk';
import * as fs from 'fs';
import * as path from 'path';
import { ModuleLoader } from '../core/module-loader';
import {
  calculateModuleCharacterCount,
  compareSemanticVersions,
  findModule,
  getModulesDir,
  validateModuleStructure,
  type Module
} from '../utils/module-system';
import {
  loadExtensionsConfig,
  pinModuleVersion as persistPinnedModuleVersion,
  type LinkedModuleRecord
} from '../utils/extensions-config';

interface CreateOptions {
  type?: string;
}

const VALID_MODULE_TYPES = [
  'coding-standards',
  'domain-rules',
  'workflows',
  'examples',
  'marketing-standards',
  'writing-standards',
  'themes'
] as const;

type ModuleType = (typeof VALID_MODULE_TYPES)[number];

interface LinkedModuleInspection {
  module: Module;
  linkedEntry: LinkedModuleRecord;
  latestVersion: string;
  latestModule: Module;
}

function toDisplayName(name: string): string {
  return name
    .split(/[-_\s]+/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(' ');
}

function isValidModuleType(type: string): type is ModuleType {
  return (VALID_MODULE_TYPES as readonly string[]).includes(type);
}

function isValidModuleName(name: string): boolean {
  return /^[A-Za-z0-9][A-Za-z0-9._-]*$/.test(name) && !name.includes('..');
}

function writeJson(filePath: string, data: unknown): void {
  fs.writeFileSync(filePath, JSON.stringify(data, null, 2), 'utf-8');
}

function buildChangelog(version: string): string {
  const date = new Date().toISOString().slice(0, 10);

  return [
    '# Changelog',
    '',
    `## [${version}] - ${date}`,
    '',
    '### Added',
    '- Initial scaffold generated by `augx create`.',
    ''
  ].join('\n');
}

function createModuleScaffold(
  modulePath: string,
  moduleName: string,
  moduleType: ModuleType
): void {
  const displayName = toDisplayName(moduleName);
  const version = '1.0.0';
  const publishedAt = new Date().toISOString();
  const ruleFilename = 'starter-rule.md';
  const readmePath = path.join(modulePath, 'README.md');
  const versionPath = path.join(modulePath, 'VERSION');
  const changelogPath = path.join(modulePath, 'CHANGELOG.md');
  const moduleJsonPath = path.join(modulePath, 'module.json');
  const metadataJsonPath = path.join(modulePath, 'metadata.json');

  const moduleJson = {
    name: moduleName,
    version,
    displayName,
    description: `${displayName} module scaffold`,
    type: moduleType,
    author: 'Augment Extensions',
    license: 'MIT',
    tags: [moduleName, moduleType, 'starter'],
    dependencies: [],
    files: [
      'README.md',
      'VERSION',
      'CHANGELOG.md',
      'metadata.json',
      `rules/${ruleFilename}`
    ],
    augment: {
      characterCount: 0,
      priority: 'medium',
      category: moduleType
    }
  };

  const metadataJson = {
    version,
    name: moduleName,
    displayName,
    description: `${displayName} module scaffold`,
    type: moduleType,
    tags: [moduleName, moduleType, 'starter'],
    compatibility: {
      augmentMinVersion: '1.0.0',
      nodeMinVersion: '18.0.0'
    },
    characterCount: 0,
    publishedAt,
    changelog: 'CHANGELOG.md',
    lastUpdated: publishedAt.slice(0, 10),
    files: {
      rules: [ruleFilename],
      examples: []
    }
  };

  fs.mkdirSync(path.join(modulePath, 'rules'), { recursive: true });
  fs.mkdirSync(path.join(modulePath, 'examples'), { recursive: true });

  fs.writeFileSync(
    readmePath,
    [
      `# ${displayName}`,
      '',
      'Starter module scaffold generated by `augx create`.',
      '',
      '## Overview',
      '',
      'Describe what this module should teach Augment Code AI to do.',
      '',
      '## Installation',
      '',
      '```bash',
      `augx link ${moduleType}/${moduleName}`,
      '```',
      '',
      '## Contents',
      '',
      `- \`rules/${ruleFilename}\` - Replace this starter rule with real guidance.`,
      ''
    ].join('\n'),
    'utf-8'
  );

  fs.writeFileSync(
    path.join(modulePath, 'rules', ruleFilename),
    [
      '# Starter Rule',
      '',
      'Replace this scaffold with module-specific guidance.',
      '',
      '## What to do next',
      '',
      '- Describe the behavior the module should enforce.',
      '- Add examples or edge cases as needed.',
      ''
    ].join('\n'),
    'utf-8'
  );

  fs.writeFileSync(versionPath, `${version}\n`, 'utf-8');
  fs.writeFileSync(changelogPath, buildChangelog(version), 'utf-8');
  writeJson(moduleJsonPath, moduleJson);
  writeJson(metadataJsonPath, metadataJson);

  let characterCount = 0;

  for (let iteration = 0; iteration < 3; iteration++) {
    moduleJson.augment.characterCount = characterCount;
    metadataJson.characterCount = characterCount;

    writeJson(moduleJsonPath, moduleJson);
    writeJson(metadataJsonPath, metadataJson);

    const nextCharacterCount = calculateModuleCharacterCount(modulePath);
    if (nextCharacterCount === characterCount) {
      break;
    }

    characterCount = nextCharacterCount;
  }

  moduleJson.augment.characterCount = characterCount;
  metadataJson.characterCount = characterCount;
  writeJson(moduleJsonPath, moduleJson);
  writeJson(metadataJsonPath, metadataJson);

  const validation = validateModuleStructure(modulePath);
  if (!validation.valid) {
    throw new Error(validation.errors.join('; '));
  }
}

function getLatestModuleInspection(linkedEntry: LinkedModuleRecord): LinkedModuleInspection | null {
  const module = findModule(linkedEntry.name);
  if (!module) {
    return null;
  }

  const latestResult = new ModuleLoader().load(module.path, { version: 'latest' });
  if (!latestResult) {
    return null;
  }

  return {
    module,
    linkedEntry,
    latestVersion: latestResult.version,
    latestModule: latestResult.module
  };
}

function getChangelogPreview(modulePath: string, maxLines: number = 16): string[] {
  const changelogPath = path.join(modulePath, 'CHANGELOG.md');
  if (!fs.existsSync(changelogPath)) {
    return [];
  }

  const lines = fs.readFileSync(changelogPath, 'utf-8').replace(/\r\n/g, '\n').split('\n');
  const firstVersionLine = lines.findIndex((line, index) => index > 0 && line.startsWith('## '));

  if (firstVersionLine < 0) {
    return lines.slice(0, Math.min(lines.length, maxLines));
  }

  let end = lines.length;
  for (let index = firstVersionLine + 1; index < lines.length; index++) {
    if (lines[index].startsWith('## ')) {
      end = index;
      break;
    }
  }

  return lines.slice(firstVersionLine, Math.min(end, firstVersionLine + maxLines));
}

function findLinkedEntry(
  configEntries: LinkedModuleRecord[],
  moduleName: string,
  moduleFullName: string
): LinkedModuleRecord | undefined {
  return configEntries.find((entry) =>
    entry.name === moduleFullName || entry.name === moduleName || entry.name.endsWith(`/${moduleName}`)
  );
}

export async function createCommand(name: string, options: CreateOptions = {}): Promise<void> {
  try {
    const moduleName = name.trim();
    const moduleType = (options.type || 'coding-standards').trim();

    console.log(chalk.green(`Creating new module: ${moduleName}`));
    console.log(chalk.gray(`Type: ${moduleType}`));

    if (!moduleName) {
      console.error(chalk.red('✗ Module name is required'));
      process.exit(1);
    }

    if (!isValidModuleName(moduleName)) {
      console.error(chalk.red(`✗ Invalid module name: ${moduleName}`));
      console.log(chalk.gray('  Use a simple slug like "my-module".'));
      process.exit(1);
    }

    if (!isValidModuleType(moduleType)) {
      console.error(chalk.red(`✗ Invalid module type: ${moduleType}`));
      console.log(
        chalk.gray(`  Valid types: ${VALID_MODULE_TYPES.join(', ')}`)
      );
      process.exit(1);
    }

    const modulesRoot = getModulesDir();
    const modulePath = path.join(modulesRoot, moduleType, moduleName);

    if (fs.existsSync(modulePath)) {
      console.error(chalk.red(`✗ Module already exists: ${moduleType}/${moduleName}`));
      process.exit(1);
    }

    createModuleScaffold(modulePath, moduleName, moduleType);

    console.log(chalk.green(`✓ Created module scaffold at ${moduleType}/${moduleName}`));
    console.log(chalk.gray(`  Location: ${modulePath}`));
    console.log(chalk.gray('  Files: module.json, metadata.json, VERSION, README.md, CHANGELOG.md, rules/starter-rule.md'));
    console.log(chalk.gray(`\nUse "augx validate ${moduleType}/${moduleName}" to verify the scaffold.`));
  } catch (error) {
    console.error(chalk.red('Error creating module:'), error);
    process.exit(1);
  }
}

export async function pinCommand(moduleName: string, version: string): Promise<void> {
  try {
    console.log(chalk.cyan(`Pinning ${moduleName} to version ${version}`));

    const module = findModule(moduleName);
    if (!module) {
      console.error(chalk.red(`Module not found: ${moduleName}`));
      process.exit(1);
    }

    persistPinnedModuleVersion(module.fullName, version);

    console.log(chalk.green(`✓ Pinned ${module.fullName} to v${version}`));
    console.log(chalk.cyan('  📌 Version pinned to config'));
  } catch (error) {
    console.error(chalk.red('Error pinning module:'), error);
    process.exit(1);
  }
}

export async function checkUpdatesCommand(): Promise<void> {
  try {
    console.log(chalk.blue('Checking for updates...'));

    const projectRoot = process.cwd();
    const configResult = loadExtensionsConfig(projectRoot);

    if (!configResult.exists) {
      console.error(chalk.red('Augment Extensions not initialized. Run: augx init'));
      process.exit(1);
    }

    if (!configResult.valid) {
      console.error(
        chalk.red(`Invalid extensions config: ${configResult.error || 'unknown error'}`)
      );
      process.exit(1);
    }

    const modules = configResult.config.modules;

    if (modules.length === 0) {
      console.log(chalk.yellow('No modules linked. Use "augx link <module>" to link modules.'));
      return;
    }

    let updatesAvailable = 0;
    let upToDate = 0;
    let aheadOfRepo = 0;
    let errors = 0;

    for (const linkedEntry of modules) {
      const inspection = getLatestModuleInspection(linkedEntry);

      if (!inspection) {
        errors++;
        console.log(chalk.red(`✗ ${linkedEntry.name}: Module not found or could not be loaded`));
        continue;
      }

      try {
        const comparison = compareSemanticVersions(inspection.latestVersion, linkedEntry.version);
        if (comparison > 0) {
          updatesAvailable++;
          console.log(
            chalk.yellow(`↗ ${inspection.module.fullName}: Update available ${linkedEntry.version} → ${inspection.latestVersion}`)
          );
        } else if (comparison < 0) {
          aheadOfRepo++;
          console.log(
            chalk.gray(
              `⚠ ${inspection.module.fullName}: Linked version (${linkedEntry.version}) is newer than available (${inspection.latestVersion})`
            )
          );
        } else {
          upToDate++;
          console.log(chalk.green(`✓ ${inspection.module.fullName}: Up to date (${linkedEntry.version})`));
        }
      } catch (error) {
        errors++;
        console.log(
          chalk.red(
            `✗ ${inspection.module.fullName}: Invalid version data (${linkedEntry.version} vs ${inspection.latestVersion})`
          )
        );
      }
    }

    console.log(chalk.bold('\nSummary'));
    console.log(chalk.gray(`  Up to date: ${upToDate}`));
    console.log(chalk.gray(`  Updates available: ${updatesAvailable}`));
    console.log(chalk.gray(`  Ahead of repo: ${aheadOfRepo}`));
    console.log(chalk.gray(`  Errors: ${errors}`));

    if (updatesAvailable > 0 || errors > 0) {
      console.log(chalk.gray('\nUse "augx diff <module>" to review a module before upgrading.'));
      process.exit(1);
    }
  } catch (error) {
    console.error(chalk.red('Error checking for updates:'), error);
    process.exit(1);
  }
}

export async function diffCommand(moduleName: string): Promise<void> {
  try {
    console.log(chalk.magenta(`Showing diff for: ${moduleName}`));

    const projectRoot = process.cwd();
    const configResult = loadExtensionsConfig(projectRoot);

    if (!configResult.exists) {
      console.error(chalk.red('Augment Extensions not initialized. Run: augx init'));
      process.exit(1);
    }

    if (!configResult.valid) {
      console.error(
        chalk.red(`Invalid extensions config: ${configResult.error || 'unknown error'}`)
      );
      process.exit(1);
    }

    const module = findModule(moduleName);
    if (!module) {
      console.error(chalk.red(`Module not found: ${moduleName}`));
      process.exit(1);
    }

    const linkedEntry = findLinkedEntry(configResult.config.modules, moduleName, module.fullName);
    if (!linkedEntry) {
      console.error(chalk.red(`Module is not linked in this project: ${module.fullName}`));
      console.log(chalk.gray(`Use "augx link ${module.fullName}" to add it before diffing.`));
      process.exit(1);
    }

    const inspection = getLatestModuleInspection(linkedEntry);
    if (!inspection) {
      console.error(chalk.red(`Unable to load latest version for ${module.fullName}`));
      process.exit(1);
    }

    const comparison = compareSemanticVersions(inspection.latestVersion, linkedEntry.version);
    const versionCurrent = linkedEntry.version;
    const versionLatest = inspection.latestVersion;

    console.log(chalk.bold('\nCurrent vs Latest'));
    console.log(chalk.gray(`  Current: ${versionCurrent}`));
    console.log(chalk.gray(`  Latest:  ${versionLatest}`));

    if (comparison === 0) {
      console.log(chalk.green('  ✓ No version change detected'));
    } else if (comparison > 0) {
      console.log(chalk.yellow(`  ↗ Update available: ${versionCurrent} → ${versionLatest}`));
    } else {
      console.log(
        chalk.yellow(`  ⚠ Linked version (${versionCurrent}) is newer than available (${versionLatest})`)
      );
    }

    if (typeof linkedEntry.description === 'string' && linkedEntry.description !== inspection.latestModule.metadata.description) {
      console.log(chalk.bold('\nDescription'));
      console.log(chalk.gray(`  Current: ${linkedEntry.description}`));
      console.log(chalk.gray(`  Latest:  ${inspection.latestModule.metadata.description}`));
    }

    console.log(chalk.bold('\nModule Contents'));
    console.log(chalk.gray(`  Rules: ${inspection.latestModule.rules.length}`));
    console.log(chalk.gray(`  Examples: ${inspection.latestModule.examples.length}`));

    const preview = getChangelogPreview(inspection.module.path);
    if (preview.length > 0) {
      console.log(chalk.bold('\nLatest Changes'));
      preview.forEach((line) => console.log(chalk.gray(`  ${line}`)));
    } else {
      console.log(chalk.gray('\nNo CHANGELOG.md found for this module.'));
    }

    console.log(chalk.gray(`\nUse "augx upgrade ${inspection.module.fullName}" to apply the latest version.`));
  } catch (error) {
    console.error(chalk.red('Error showing diff:'), error);
    process.exit(1);
  }
}
